// <auto-generated />
using System;
using MedicoDent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicoDent.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212211117_AddedPatientInfoAndPatientContactTableAndGroup")]
    partial class AddedPatientInfoAndPatientContactTableAndGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("MedicoDent.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientGroupId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientBasicInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriageStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Workplace")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientBasicInfos");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientContacts");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatientGroups");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.PatientGroup", "PatientGroup")
                        .WithMany()
                        .HasForeignKey("PatientGroupId");

                    b.Navigation("PatientGroup");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientBasicInfo", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithOne("PatientBasicInfo")
                        .HasForeignKey("MedicoDent.Domain.Entities.PatientBasicInfo", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientContact", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithOne("PatientContact")
                        .HasForeignKey("MedicoDent.Domain.Entities.PatientContact", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Patient", b =>
                {
                    b.Navigation("PatientBasicInfo");

                    b.Navigation("PatientContact");
                });
#pragma warning restore 612, 618
        }
    }
}
