// <auto-generated />
using System;
using MedicoDent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicoDent.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309143129_FixingMigrations")]
    partial class FixingMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("MedicoDent.Domain.Entities.Allergie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.MedicoService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAllergie")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlackListed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasAllergie = false,
                            IsBlackListed = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientAllergies", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllergieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatientId", "AllergieId");

                    b.HasIndex("AllergieId");

                    b.ToTable("PatientAllergies", (string)null);
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientBasicInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalHealthInsuranceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthInsuranceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriageStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Workplace")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientBasicInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Guzica",
                            LastName = "Doe",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Doe",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            LastName = "Doe",
                            PatientId = 4
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jill",
                            LastName = "Doe",
                            PatientId = 5
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            LastName = "Doe",
                            PatientId = 6
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jenny",
                            LastName = "Doe",
                            PatientId = 7
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Doe",
                            PatientId = 8
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jessica",
                            LastName = "Doe",
                            PatientId = 9
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            LastName = "Doe",
                            PatientId = 10
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            LastName = "Doe",
                            PatientId = 11
                        });
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientContact", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientContacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatientGroups");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientGroupMembership", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientGroupTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatientId", "GroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PatientGroupTemplateId");

                    b.ToTable("PatientPatientGroups", (string)null);
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientGroupTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatientGroupTemplates");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TreatmentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.TreatmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TreatmentStatuses");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "afLqazWAGp6E1TNsBhYdCIb74Jk=",
                            PasswordSalt = "tiz+F67+SJs5O3AAeAsFpw==",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientAllergies", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.Allergie", "Allergie")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("AllergieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergie");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientBasicInfo", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithOne("PatientBasicInfo")
                        .HasForeignKey("MedicoDent.Domain.Entities.PatientBasicInfo", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientContact", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithOne("PatientContact")
                        .HasForeignKey("MedicoDent.Domain.Entities.PatientContact", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientGroupMembership", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.PatientGroup", "PatientGroup")
                        .WithMany("PatientGroupsMembership")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicoDent.Domain.Entities.PatientGroupTemplate", "PatientGroupTemplate")
                        .WithMany()
                        .HasForeignKey("PatientGroupTemplateId");

                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientGroupsMembership")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PatientGroup");

                    b.Navigation("PatientGroupTemplate");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Treatment", b =>
                {
                    b.HasOne("MedicoDent.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicoDent.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicoDent.Domain.Entities.MedicoService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Allergie", b =>
                {
                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.Patient", b =>
                {
                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientBasicInfo");

                    b.Navigation("PatientContact");

                    b.Navigation("PatientGroupsMembership");
                });

            modelBuilder.Entity("MedicoDent.Domain.Entities.PatientGroup", b =>
                {
                    b.Navigation("PatientGroupsMembership");
                });
#pragma warning restore 612, 618
        }
    }
}
